### PR TITLE
update flags HTTP server address & NATS broker address.

### PR DESCRIPTION
**Pull request by m-abdalrahman**
update flags HTTP server address & NATS broker address default values,
to solve problem  `Connection reset by peer`  which occur from docker container.

### CODE REVIEW

**Comment by drasko** [comment]
Why does this happen exactly? Normally inside Docker container you will use other NATS host address: https://github.com/mainflux/mainflux-http-sender/blob/master/Dockerfile#L21

I am not apriori against this change, I just want to understand why the mentioned errors happens.

**Comment by nmarcetic** [comment]
@m-abdalrahman When you see this error `Connection reset by peer` ? I worked on this service few days ago, testing HTTP API (using dockerized service), didn't see this error. As @drasko said, we want to check why this error occur and when before we accept PR. Thanks ;)

**Comment by m-abdalrahman** [comment]
This problem occurred when I tried to check if service work by using command
`curl serverIP:7070/status` or`curl localhost:7070/status` I get this error message 

> curl: (56) Recv failure: Connection reset by peer

and when I check container logs I get this message

> 2017/05/26 09:44:33 Connecting to NATS...
> 2017/05/26 09:44:33 OK

after I changed the code form **localhost** to **0.0.0.0** this problem disappeared
https://stackoverflow.com/a/27818259
also this problem appears for [mainflux-influxdb-reader](https://github.com/mainflux/mainflux-influxdb-reader), and [mainflux-influxdb-writer](https://github.com/mainflux/mainflux-influxdb-writer).

**Comment by drasko** [comment]
@m-abdalrahman are you issuing `curl localhost:7070/status` from the host (from which you are running Docker container), or are you logging into the Docker container and trying `curl` from within the container? Because Docker port 7070 is mapped to host's port 7070 and should be accessible on `localhost:7070` - https://github.com/mainflux/mainflux/blob/master/docker-compose.yml#L70

**Comment by m-abdalrahman** [comment]
@drasko from the host.

**Comment by drasko** [comment]
@mijicd do you see the same error? @manuIO what about you?

@m-abdalrahman for your PR to be requested you must show us what and more importantly in this case **why** is something wrong (because in this case we still can not figure out if something is wrong with your host, or is it Mainflux code that should be changed - especially for the fact that `localhost`  should work, and that it is working for the rest of us).

**Comment by manuIO** [comment]
👍  That's what I thought too

**Comment by drasko** [comment]
@nmarcetic @mijicd trying to make Docker two-stage build I ended up with the same issue. When address is `0.0,0.0` then `curl` from the host works, i.e. server is container is reachable. Otherwise with `localhost` I am getting 
```
curl: (56) Recv failure: Connection reset by peer
```

I have no idea why... For other containers it works, though... But they were pulled from DockerHub. Can it be that build introduces some weird stuff?

**Comment by drasko** [comment]
OK, finally I will accept this PR - we need this change. But I would like that we understand why there is a difference between `localhost` and `0.0.0.0`. I understand that docker-compose` maps `0.0.0.0` by default, but I why is this not the same as `localhost` from within the container - I do not know.

**Comment by drasko** [comment]
Merged.

**Pull request merged**
